name: pyscf-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  # Core scientific computing libraries
  - pyscf
  - rdkit
  - geometric
  - ase
  # Web framework and networking
  - flask
  - requests
  - flask-cors
  - pydantic
  - threadpoolctl
  - gunicorn
  # Development and testing dependencies
  - pytest
  - pip
  # Environment packaging for distribution
  - conda-pack
  - pip:
    # Flask extensions
    - flask-pydantic
    - flask-socketio
    # Code generation and build tools
    - datamodel-code-generator
    - pyinstaller
    # File system monitoring
    - watchdog
    # Security and certificates
    - certifi
    # Testing framework for Flask
    - pytest-flask