name: pyscf-env
channels:
  - conda-forge
dependencies:
  - python=3.12.11
  # Core scientific computing libraries
  - numpy>=2.0,<2.3  # longdouble問題を回避するため2.3より前のバージョンを使用
  - pyscf=2.10.0
  - rdkit=2025.03.6
  - geometric=1.1
  - ase=3.26.0
  # Bioinformatics (for PubMed search)
  - biopython=1.85
  # Web framework and networking
  - flask=3.1.2
  - requests=2.32.5
  - flask-cors=6.0.1
  - pydantic=2.11.7
  - threadpoolctl=3.6.0
  - gunicorn=23.0.0
  - gevent=25.8.2
  # System monitoring and resource management
  - psutil=7.0.0
  # Development and testing dependencies
  - pytest=8.4.2
  - pytest-mock=3.14.0
  - pytest-cov=6.0.0
  - pip=25.2
  # Environment packaging for distribution
  - conda-pack=0.8.1
  - pip:
    # Flask extensions
    - flask-pydantic==0.13.2
    - flask-socketio==5.5.1
    - flask-sock==0.7.0
    # Code generation and build tools
    - datamodel-code-generator==0.33.0
    # File system monitoring
    - watchdog==6.0.0
    # Testing framework for Flask
    - pytest-flask==1.3.0
    # AI/ML API integration
    - google-genai==1.39.1
    # LangChain ecosystem for multi-agent architecture
    - langchain==0.3.27
    - langgraph==0.6.8
    - langchain-google-genai==2.1.12
    - langgraph-supervisor==0.0.29
    # Research agent search tools
    - arxiv==2.2.0              # arXiv preprint search
    - langchain-tavily==0.2.12  # Tavily web search integration
    - chemrxiv                  # Chemistry preprint search (latest from June 2025)
    - pyalex==0.18              # OpenAlex comprehensive academic search
    - semanticscholar==0.9.0    # Semantic Scholar AI/ML/science papers