"""Unit tests for molecular orbital CUBE file generation."""

import os
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from quantum_calc.exceptions import CalculationError
from quantum_calc.orbital_generator import MolecularOrbitalGenerator


VALID_CUBE_DATA = """Generated by test
Orbital cube
2 0.0 0.0 0.0
1 1.0 0.0 0.0
1 0.0 1.0 0.0
1 0.0 0.0 1.0
1 1.0 0.0 0.0 0.0
1 1.0 0.0 0.0 0.7
0.0 0.1
"""


def _make_generator(tmp_path: Path) -> MolecularOrbitalGenerator:
    generator = MolecularOrbitalGenerator(str(tmp_path))
    generator.mol = object()
    generator.mf = SimpleNamespace(
        mo_coeff=np.eye(2),
        mo_energy=np.array([-0.5, 0.2]),
        mo_occ=np.array([2.0, 0.0]),
    )
    return generator


def test_generate_cube_file_save_to_disk_uses_atomic_replace(tmp_path, mocker) -> None:
    """
    GIVEN cubegen successfully writes a CUBE file
    WHEN a persistent orbital cube is generated
    THEN the final cache file is installed via os.replace from a temp file
    """
    generator = _make_generator(tmp_path)
    written_paths = []

    def write_cube(
        _mol: object,
        filename: str,
        _coeff: object,
        nx: int,
        ny: int,
        nz: int,
    ) -> None:
        written_paths.append(Path(filename))
        Path(filename).write_text(VALID_CUBE_DATA, encoding="utf-8")

    mocker.patch(
        "quantum_calc.orbital_generator.tools.cubegen.orbital",
        side_effect=write_cube,
    )
    replace_spy = mocker.patch(
        "quantum_calc.orbital_generator.os.replace",
        wraps=os.replace,
    )

    result = generator.generate_cube_file(
        orbital_index=1,
        grid_size=40,
        return_content=True,
        save_to_disk=True,
    )

    final_path = tmp_path / "orbital" / "orbital_1_grid40.cube"
    replace_spy.assert_called_once()
    temp_path, replace_target = replace_spy.call_args.args

    assert Path(replace_target) == final_path
    assert Path(temp_path).parent == final_path.parent
    assert Path(temp_path).name != final_path.name
    assert written_paths == [Path(temp_path)]
    assert final_path.read_text(encoding="utf-8") == VALID_CUBE_DATA
    assert result["cube_data"] == VALID_CUBE_DATA
    assert result["file_path"] == str(final_path)
    assert result["cached"] is False


def test_generate_cube_file_removes_temp_file_when_cubegen_fails(tmp_path, mocker) -> None:
    """
    GIVEN cubegen writes partial data and then fails
    WHEN a persistent orbital cube is generated
    THEN no broken final cache file remains
    """
    generator = _make_generator(tmp_path)

    def write_partial_then_fail(
        _mol: object,
        filename: str,
        _coeff: object,
        nx: int,
        ny: int,
        nz: int,
    ) -> None:
        Path(filename).write_text("partial cube data", encoding="utf-8")
        raise RuntimeError("cubegen failed")

    mocker.patch(
        "quantum_calc.orbital_generator.tools.cubegen.orbital",
        side_effect=write_partial_then_fail,
    )

    with pytest.raises(CalculationError, match="CUBE file generation failed"):
        generator.generate_cube_file(
            orbital_index=0,
            grid_size=40,
            return_content=True,
            save_to_disk=True,
        )

    orbital_dir = tmp_path / "orbital"
    final_path = orbital_dir / "orbital_0_grid40.cube"
    assert not final_path.exists()
    assert list(orbital_dir.glob("*.cube")) == []


def test_generate_cube_file_regenerates_invalid_existing_cache(tmp_path, mocker) -> None:
    """
    GIVEN an existing CUBE path contains invalid partial data
    WHEN a persistent orbital cube is generated
    THEN the invalid cache is not returned as a cache hit
    """
    generator = _make_generator(tmp_path)
    orbital_dir = tmp_path / "orbital"
    orbital_dir.mkdir()
    final_path = orbital_dir / "orbital_0_grid40.cube"
    final_path.write_text("partial cube data", encoding="utf-8")

    def write_cube(
        _mol: object,
        filename: str,
        _coeff: object,
        nx: int,
        ny: int,
        nz: int,
    ) -> None:
        Path(filename).write_text(VALID_CUBE_DATA, encoding="utf-8")

    cubegen_orbital = mocker.patch(
        "quantum_calc.orbital_generator.tools.cubegen.orbital",
        side_effect=write_cube,
    )

    result = generator.generate_cube_file(
        orbital_index=0,
        grid_size=40,
        return_content=True,
        save_to_disk=True,
    )

    cubegen_orbital.assert_called_once()
    assert final_path.read_text(encoding="utf-8") == VALID_CUBE_DATA
    assert result["cube_data"] == VALID_CUBE_DATA
    assert result["cached"] is False
