name: pyscf_front
description: Quantum chemistry calculation native application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.1.4
  
  # gRPC
  grpc: ^4.0.0
  protobuf: ^3.1.0
  
  # 3D Visualization
  flutter_gl: ^0.0.21
  vector_math: ^2.1.4
  
  # File Operations
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  
  # Database
  sqflite: ^2.3.3
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0
  logger: ^2.3.0
  
  # Charts
  fl_chart: ^0.68.0
  
  # Platform specific (desktop only)
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
  
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700