# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SearchType(Enum):
    """
    Type of PubChem search
    """

    name = 'name'
    cid = 'cid'
    formula = 'formula'


class SolventMethod(Enum):
    """
    Solvent calculation method
    """

    none = 'none'
    ief_pcm = 'ief-pcm'
    c_pcm = 'c-pcm'
    cosmo = 'cosmo'
    ssvpe = 'ssvpe'
    ddcosmo = 'ddcosmo'


class CalculationMethod(Enum):
    """
    Quantum calculation method
    """

    DFT = 'DFT'
    HF = 'HF'
    MP2 = 'MP2'
    CCSD = 'CCSD'
    CCSD_T = 'CCSD_T'
    TDDFT = 'TDDFT'
    CASCI = 'CASCI'
    CASSCF = 'CASSCF'


class CalculationStatus(Enum):
    """
    Status of a calculation
    """

    pending = 'pending'
    running = 'running'
    completed = 'completed'
    error = 'error'
    waiting = 'waiting'
    pausing = 'pausing'
    paused = 'paused'


class PubChemSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str = Field(
        ..., description='Search query for PubChem', max_length=500, min_length=1
    )
    searchType: Optional[SearchType] = 'name'


class SMILESConvertRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    smiles: str = Field(
        ...,
        description='SMILES string to convert to XYZ format',
        max_length=10000,
        min_length=1,
    )


class XYZValidateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    xyz: str = Field(
        ..., description='XYZ string to validate', max_length=1000000, min_length=1
    )


class CalculationRequestBase(BaseModel):
    xyz: str = Field(
        ...,
        description='XYZ molecular structure data (chemistry-aware cap ~1 MB)',
        max_length=1000000,
        min_length=1,
    )
    calculation_method: CalculationMethod
    basis_function: Optional[str] = Field(
        None,
        description='Basis set for calculation (e.g., STO-3G, 6-31G(d), cc-pVDZ)',
        max_length=200,
    )
    charges: Optional[int] = Field(0, description='Molecular charge', ge=-10, le=10)
    spin: Optional[int] = Field(
        0, description='Spin (2S), number of unpaired electrons', ge=0, le=10
    )
    solvent_method: Optional[SolventMethod] = 'none'
    solvent: Optional[str] = Field(
        '-',
        description='Solvent type or custom parameters. Options include:\n- Predefined solvents: water, dimethylsulfoxide, n,n-dimethylformamide, etc.\n- Custom dielectric constant (numeric value > 1.0)\n',
        max_length=200,
    )
    name: Optional[str] = Field(
        'Unnamed Calculation',
        description='Display name for the calculation instance',
        max_length=100,
        min_length=1,
    )
    cpu_cores: Optional[int] = Field(
        None, description='Number of CPU cores', ge=1, le=32
    )
    memory_mb: Optional[int] = Field(None, description='Memory in MB', ge=512, le=32768)
    ketcher_data: Optional[str] = Field(
        None, description='Ketcher molecule format (JSON)', max_length=1000000
    )


class CalculationMethod1(Enum):
    DFT = 'DFT'


class DFTCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['DFT']
    exchange_correlation: Optional[str] = Field(
        'B3LYP',
        description='Exchange-correlation functional (e.g., B3LYP, PBE0, M06-2X)',
        max_length=200,
    )
    basis_function: Optional[str] = '6-31G(d)'
    optimize_geometry: Optional[bool] = Field(
        True, description='Whether to perform geometry optimization'
    )
    geomopt_maxsteps: Optional[int] = Field(
        100, description='Maximum number of geometry optimization steps', ge=1, le=1000
    )
    geomopt_conv_energy: Optional[float] = Field(
        1e-06, description='Energy convergence threshold (Hartree)'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod2(Enum):
    HF = 'HF'


class HFCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['HF']
    basis_function: Optional[str] = '6-31G(d)'
    optimize_geometry: Optional[bool] = True
    geomopt_maxsteps: Optional[int] = Field(
        100, description='Maximum number of geometry optimization steps', ge=1, le=1000
    )
    geomopt_conv_energy: Optional[float] = Field(
        1e-06, description='Energy convergence threshold (Hartree)'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod3(Enum):
    MP2 = 'MP2'


class MP2CalculationRequest(CalculationRequestBase):
    calculation_method: Literal['MP2']
    basis_function: Optional[str] = '6-31G(d)'
    optimize_geometry: Optional[bool] = True
    geomopt_maxsteps: Optional[int] = Field(
        100, description='Maximum number of geometry optimization steps', ge=1, le=1000
    )
    geomopt_conv_energy: Optional[float] = Field(
        1e-06, description='Energy convergence threshold (Hartree)'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod4(Enum):
    CCSD = 'CCSD'


class CCSDCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['CCSD']
    basis_function: Optional[str] = 'cc-pVDZ'
    frozen_core: Optional[bool] = Field(
        True, description='Use frozen core approximation to reduce computational cost'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod5(Enum):
    CCSD_T = 'CCSD_T'


class CCSDTCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['CCSD_T']
    basis_function: Optional[str] = 'cc-pVDZ'
    frozen_core: Optional[bool] = Field(
        True, description='Use frozen core approximation'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod6(Enum):
    TDDFT = 'TDDFT'


class TddftMethod(Enum):
    """
    TDDFT or Tamm-Dancoff approximation
    """

    TDDFT = 'TDDFT'
    TDA = 'TDA'


class TDDFTCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['TDDFT']
    exchange_correlation: Optional[str] = Field(
        'B3LYP', description='Exchange-correlation functional', max_length=200
    )
    basis_function: Optional[str] = '6-31G(d)'
    tddft_nstates: Optional[int] = Field(
        10, description='Number of excited states to calculate', ge=1, le=50
    )
    tddft_method: Optional[TddftMethod] = Field(
        'TDDFT', description='TDDFT or Tamm-Dancoff approximation'
    )
    tddft_analyze_nto: Optional[bool] = Field(
        False, description='Perform Natural Transition Orbital analysis'
    )
    density_fitting: Optional[bool] = Field(
        False,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
        max_length=200,
    )


class CalculationMethod7(Enum):
    CASCI = 'CASCI'


class CASCICalculationRequest(CalculationRequestBase):
    calculation_method: Literal['CASCI']
    basis_function: Optional[str] = '6-31G(d)'
    ncas: int = Field(..., description='Number of active space orbitals', ge=1, le=20)
    nelecas: int = Field(
        ..., description='Number of active space electrons', ge=1, le=40
    )
    max_cycle_micro: Optional[int] = Field(
        3, description='Maximum CI solver micro iterations', ge=1, le=100
    )
    natorb: Optional[bool] = Field(
        True, description='Transform to natural orbitals in active space'
    )


class CalculationMethod8(Enum):
    CASSCF = 'CASSCF'


class CASSCFCalculationRequest(CalculationRequestBase):
    calculation_method: Literal['CASSCF']
    basis_function: Optional[str] = '6-31G(d)'
    ncas: int = Field(..., description='Number of active space orbitals', ge=1, le=20)
    nelecas: int = Field(
        ..., description='Number of active space electrons', ge=1, le=40
    )
    max_cycle_macro: Optional[int] = Field(
        50, description='Maximum CASSCF macro iterations', ge=1, le=200
    )
    max_cycle_micro: Optional[int] = Field(
        3, description='Maximum CI solver micro iterations', ge=1, le=100
    )
    natorb: Optional[bool] = Field(True, description='Transform to natural orbitals')
    conv_tol: Optional[float] = Field(
        1e-06, description='Energy convergence tolerance', ge=1e-12, le=0.001
    )
    conv_tol_grad: Optional[float] = Field(
        0.0001, description='Gradient convergence tolerance', ge=1e-08, le=0.01
    )


class QuantumCalculationRequest(
    RootModel[
        Union[
            DFTCalculationRequest,
            HFCalculationRequest,
            MP2CalculationRequest,
            CCSDCalculationRequest,
            CCSDTCalculationRequest,
            TDDFTCalculationRequest,
            CASCICalculationRequest,
            CASSCFCalculationRequest,
        ]
    ]
):
    root: Union[
        DFTCalculationRequest,
        HFCalculationRequest,
        MP2CalculationRequest,
        CCSDCalculationRequest,
        CCSDTCalculationRequest,
        TDDFTCalculationRequest,
        CASCICalculationRequest,
        CASSCFCalculationRequest,
    ] = Field(..., discriminator='calculation_method')


class CalculationUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Updated name for the calculation',
        max_length=100,
        min_length=1,
    )


class HealthResponse(BaseModel):
    status: str = Field(..., examples=['ok'])
    service: str = Field(..., examples=['pyscf-front-api'])
    version: str = Field(..., examples=['0.3.0'])


class PubChemCompoundInfo(BaseModel):
    cid: int = Field(..., description='PubChem Compound ID')
    iupac_name: str = Field(..., description='IUPAC name')
    molecular_formula: str = Field(..., description='Molecular formula')
    molecular_weight: float = Field(..., description='Molecular weight')
    synonyms: List[str] = Field(..., description='List of synonyms')


class Data(BaseModel):
    xyz: str = Field(..., description='XYZ format molecular structure')
    compound_info: PubChemCompoundInfo
    atom_count: int = Field(..., description='Number of atoms in the molecule')


class PubChemSearchResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data


class Data1(BaseModel):
    xyz: str = Field(..., description='XYZ format molecular structure')


class SMILESConvertResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data1 = Field(..., title='SMILESConvertData')


class Atom(BaseModel):
    element: str = Field(..., description='Element symbol')
    x: float = Field(..., description='X coordinate')
    y: float = Field(..., description='Y coordinate')
    z: float = Field(..., description='Z coordinate')


class Data2(BaseModel):
    """
    Validation result
    """

    valid: bool = Field(..., description='Whether the XYZ format is valid')
    error: Optional[str] = Field(None, description='Error message if validation failed')
    num_atoms: Optional[int] = Field(
        None, description='Number of atoms in the molecule (if valid)'
    )
    title: Optional[str] = Field(
        None, description='Title line from XYZ file (if valid)'
    )
    atoms: Optional[List[Atom]] = Field(
        None, description='Array of atom data (if valid)'
    )


class XYZValidateResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data2 = Field(..., description='Validation result')


class CalculationParameters(BaseModel):
    calculation_method: CalculationMethod
    basis_function: str
    exchange_correlation: Optional[str] = Field(
        None,
        description='Exchange-correlation functional. Note - This parameter is ignored for HF method as Hartree-Fock calculations do not use exchange-correlation functionals.',
    )
    charges: int
    spin: int
    solvent_method: SolventMethod
    solvent: str
    xyz: str
    molecule_name: Optional[str] = Field(
        None,
        description='Chemical name of the molecule (distinct from calculation display name)',
    )
    cpu_cores: Optional[int] = None
    memory_mb: Optional[int] = None
    gpu_acceleration_enabled: Optional[bool] = Field(
        None,
        description='GPU acceleration setting snapshot captured when the calculation job was submitted',
    )
    created_at: Optional[AwareDatetime] = None
    tddft_nstates: Optional[int] = Field(
        None, description='Number of excited states (TDDFT only)'
    )
    tddft_method: Optional[str] = Field(None, description='TDDFT method used')
    tddft_analyze_nto: Optional[bool] = Field(
        None, description='Whether NTO analysis was performed'
    )
    ncas: Optional[int] = Field(
        None, description='Number of active space orbitals (CASCI/CASSCF)'
    )
    nelecas: Optional[int] = Field(
        None, description='Number of active space electrons (CASCI/CASSCF)'
    )
    max_cycle_macro: Optional[int] = Field(
        None, description='Maximum CASSCF macro iterations'
    )
    max_cycle_micro: Optional[int] = Field(
        None, description='Maximum CI solver micro iterations'
    )
    natorb: Optional[bool] = Field(
        None, description='Whether natural orbital transformation was used'
    )
    conv_tol: Optional[float] = Field(
        None, description='Energy convergence tolerance used'
    )
    conv_tol_grad: Optional[float] = Field(
        None, description='Gradient convergence tolerance used'
    )
    geomopt_maxsteps: Optional[int] = Field(
        None, description='Maximum number of geometry optimization steps', ge=1, le=1000
    )
    geomopt_conv_energy: Optional[float] = Field(
        None, description='Energy convergence threshold (Hartree)'
    )
    density_fitting: Optional[bool] = Field(
        None,
        description='Enable density fitting (RI/DF) approximation for faster integral evaluation',
    )
    auxiliary_basis: Optional[str] = Field(
        None,
        description='Auxiliary basis set for density fitting. If null, PySCF auto-selects.',
    )
    ketcher_data: Optional[str] = Field(
        None,
        description='Ketcher molecule format (JSON) for preserving the original drawn structure',
    )


class TransitionDipole(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[float] = None


class MajorTransition(BaseModel):
    state: Optional[int] = Field(None, description='Excited state number')
    energy: Optional[float] = Field(None, description='Excitation energy in eV')
    wavelength: Optional[float] = Field(None, description='Wavelength in nm')
    oscillator_strength: Optional[float] = Field(
        None, description='Oscillator strength'
    )


class NtoPair(BaseModel):
    hole_orbital: Optional[str] = Field(
        None, description='Description of hole orbital (e.g., HOMO, HOMO-1)'
    )
    particle_orbital: Optional[str] = Field(
        None, description='Description of particle orbital (e.g., LUMO, LUMO+1)'
    )
    weight: Optional[float] = Field(None, description='NTO weight (singular value)')
    contribution: Optional[float] = Field(
        None, description='Percentage contribution to the transition'
    )
    hole_orbital_index: Optional[int] = Field(
        None, description='Index of the hole orbital'
    )
    particle_orbital_index: Optional[int] = Field(
        None, description='Index of the particle orbital'
    )


class NtoAnalysi(BaseModel):
    state: Optional[int] = Field(None, description='Excited state number (1-indexed)')
    energy: Optional[float] = Field(None, description='Excitation energy in eV')
    nto_pairs: Optional[List[NtoPair]] = Field(
        None, description='NTO orbital pairs for this excited state'
    )
    total_nto_pairs: Optional[int] = Field(
        None, description='Total number of NTO pairs analyzed'
    )


class MullikenCharge(BaseModel):
    atom_index: Optional[int] = Field(None, description='0-based index of the atom')
    element: Optional[str] = Field(
        None, description='Element symbol (e.g., C, H, O, N)'
    )
    charge: Optional[float] = Field(
        None,
        description='Mulliken charge on this atom (positive = electron deficient, negative = electron rich)',
    )


class KernelReturnInfo(BaseModel):
    """
    Information about kernel() return value structure
    """

    model_config = ConfigDict(
        extra='allow',
    )
    tuple_length: Optional[int] = Field(
        None, description='Number of elements in kernel() return tuple'
    )
    ci_coefficients_shape: Optional[str] = Field(
        None, description='Shape of CI coefficients array'
    )


class CalculationPhase(Enum):
    """
    Which phase the calculation was in when paused
    """

    geometry_optimization = 'geometry_optimization'
    scf_calculation = 'scf_calculation'
    post_scf = 'post_scf'


class ResumeInfo(BaseModel):
    """
    Information about the paused state for resuming
    """

    optimization_step: Optional[int] = Field(
        None, description='Geometry optimization step number when paused'
    )
    checkpoint_exists: Optional[bool] = Field(
        None, description='Whether checkpoint file is available for resume'
    )
    calculation_phase: Optional[CalculationPhase] = Field(
        None, description='Which phase the calculation was in when paused'
    )


class Type(Enum):
    calculation_update = 'calculation_update'
    heartbeat = 'heartbeat'
    error = 'error'


class CalculationUpdateStreamEvent(BaseModel):
    type: Type
    payload: Dict[str, Any]


class CalculationUpdateStreamErrorPayload(BaseModel):
    message: str
    calculation_id: Optional[str] = None


class CalculationSummary(BaseModel):
    id: str = Field(..., description='Unique calculation ID')
    name: str = Field(..., description='Display name')
    date: str = Field(..., description='Date string')
    status: CalculationStatus
    calculation_method: Optional[str] = Field(
        None, description='Calculation method (DFT, HF, MP2, etc.)'
    )
    basis_function: Optional[str] = Field(None, description='Basis set used')
    exchange_correlation: Optional[str] = Field(
        None, description='Exchange-correlation functional (DFT/TDDFT only)'
    )
    created_at: Optional[str] = Field(None, description='ISO format creation timestamp')


class Data4(BaseModel):
    calculations: List[CalculationSummary]
    count: int = Field(..., description='Number of calculations')


class CalculationListResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data4


class ProcessPool(BaseModel):
    max_workers: int = Field(..., ge=1)
    active_calculations: List[str] = Field(
        ..., description='Currently active calculation IDs'
    )
    active_count: int = Field(..., ge=0)
    is_shutdown: bool


class System(BaseModel):
    cpu_count: int = Field(
        ..., description='Number of CPU cores available on host machine'
    )


class Data5(BaseModel):
    process_pool: ProcessPool
    system: System


class CalculationStatusResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data5


class Files(BaseModel):
    checkpoint_exists: bool
    parameters_file_exists: bool
    results_file_exists: bool


class Data7(BaseModel):
    message: str = Field(..., examples=['Calculation renamed successfully.'])
    name: str = Field(..., description='Updated calculation name')


class CalculationUpdateResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data7


class Data8(BaseModel):
    message: str = Field(..., examples=['Calculation deleted successfully'])
    deleted_id: str = Field(..., description='ID of deleted calculation')


class CalculationDeleteResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data8


class OrbitalType(Enum):
    """
    Type of orbital
    """

    core = 'core'
    homo = 'homo'
    lumo = 'lumo'
    occupied = 'occupied'
    virtual = 'virtual'


class OrbitalInfo(BaseModel):
    index: int = Field(..., description='Orbital index (0-based)')
    energy_hartree: float = Field(..., description='Orbital energy in Hartree')
    energy_ev: float = Field(..., description='Orbital energy in eV')
    occupancy: float = Field(
        ..., description='Orbital occupancy (0.0 for virtual, 1.0 or 2.0 for occupied)'
    )
    orbital_type: OrbitalType = Field(..., description='Type of orbital')
    label: Optional[str] = Field(
        None,
        description='Human-readable label (e.g., "HOMO", "LUMO", "HOMO-1", "LUMO+2")',
    )


class Data9(BaseModel):
    orbitals: List[OrbitalInfo] = Field(
        ..., description='List of all molecular orbitals'
    )
    homo_index: int = Field(..., description='Index of HOMO orbital')
    lumo_index: int = Field(..., description='Index of LUMO orbital')
    total_orbitals: int = Field(..., description='Total number of orbitals')
    num_occupied: Optional[int] = Field(None, description='Number of occupied orbitals')
    num_virtual: Optional[int] = Field(None, description='Number of virtual orbitals')


class OrbitalsResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data9


class GenerationParams(BaseModel):
    grid_size: Optional[int] = Field(None, description='Grid size used for generation')
    isovalue_positive: Optional[float] = Field(
        None, description='Positive isovalue used'
    )
    isovalue_negative: Optional[float] = Field(
        None, description='Negative isovalue used'
    )
    file_size_kb: Optional[float] = Field(None, description='Generated file size in KB')


class Data10(BaseModel):
    cube_data: str = Field(..., description='CUBE file content as string')
    orbital_info: OrbitalInfo
    generation_params: GenerationParams
    cached: Optional[bool] = Field(
        None, description='Whether the CUBE file was loaded from cache'
    )


class OrbitalCubeResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data10


class CubeFile(BaseModel):
    filename: str = Field(..., description='Name of the CUBE file')
    orbital_index: int = Field(..., description='Index of the molecular orbital')
    grid_size: int = Field(..., description='Grid size used for generation')
    file_size_kb: float = Field(..., description='File size in KB')
    modified: AwareDatetime = Field(..., description='Last modified timestamp')


class Data11(BaseModel):
    calculation_id: str = Field(..., description='ID of the calculation')
    cube_files: List[CubeFile] = Field(..., description='List of CUBE files')
    total_files: int = Field(..., description='Total number of CUBE files')
    total_size_kb: float = Field(..., description='Total size of all CUBE files in KB')


class CubeFilesListResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data11


class Data12(BaseModel):
    calculation_id: str = Field(..., description='ID of the calculation')
    orbital_index: Optional[int] = Field(
        None, description='Orbital index that was deleted (if specific)'
    )
    deleted_files: int = Field(..., description='Number of files deleted')
    message: str = Field(..., description='Human-readable message about the deletion')


class CubeFilesDeleteResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data12


class SolventOption(BaseModel):
    value: str = Field(..., description='Solvent identifier value')
    display: str = Field(..., description='Human-readable display name')
    dielectric_constant: float = Field(
        ..., description='Dielectric constant of the solvent'
    )


class MethodDefaultValues1(BaseModel):
    """
    Default parameter values for a specific calculation method
    """

    basis_function: Optional[str] = Field(
        None, description='Default basis function for this method'
    )
    memory_mb: Optional[int] = Field(
        None, description='Default memory allocation in megabytes'
    )
    optimize_geometry: Optional[bool] = Field(
        None, description='Default geometry optimization setting'
    )
    frozen_core: Optional[bool] = Field(
        None, description='Default frozen core approximation setting (CCSD/CCSD_T)'
    )
    density_fitting: Optional[bool] = Field(
        None, description='Default density fitting setting'
    )
    tddft_nstates: Optional[int] = Field(
        None, description='Default number of excited states (TDDFT)'
    )
    tddft_method: Optional[str] = Field(
        None, description='Default TDDFT method (TDDFT)'
    )
    tddft_analyze_nto: Optional[bool] = Field(
        None, description='Default NTO analysis setting (TDDFT)'
    )
    ncas: Optional[int] = Field(
        None, description='Default number of active orbitals (CASCI/CASSCF)'
    )
    nelecas: Optional[int] = Field(
        None, description='Default number of active electrons (CASCI/CASSCF)'
    )
    max_cycle_macro: Optional[int] = Field(
        None, description='Default maximum macro iterations (CASSCF)'
    )
    max_cycle_micro: Optional[int] = Field(
        None, description='Default maximum micro iterations (CASCI/CASSCF)'
    )
    natorb: Optional[bool] = Field(
        None,
        description='Default natural orbital transformation setting (CASCI/CASSCF)',
    )
    conv_tol: Optional[float] = Field(
        None, description='Default energy convergence tolerance (CASSCF)'
    )
    conv_tol_grad: Optional[float] = Field(
        None, description='Default gradient convergence tolerance (CASSCF)'
    )
    geomopt_maxsteps: Optional[int] = Field(
        None, description='Default maximum geometry optimization steps (DFT/HF/MP2)'
    )
    geomopt_conv_energy: Optional[float] = Field(
        None,
        description='Default energy convergence threshold for geometry optimization (DFT/HF/MP2)',
    )


class MethodDefaultValues(RootModel[Optional[Dict[str, MethodDefaultValues1]]]):
    """
    Default values for each calculation method (e.g., DFT, CCSD, TDDFT)
    """

    root: Optional[Dict[str, MethodDefaultValues1]] = Field(
        None, description='Default parameter values for a specific calculation method'
    )


class ParameterConstraint(BaseModel):
    """
    Constraint definition for a calculation parameter
    """

    min: Optional[float] = Field(
        None, description='Minimum allowed value for this parameter'
    )
    max: Optional[float] = Field(
        None, description='Maximum allowed value for this parameter'
    )
    applicable_methods: Optional[List[str]] = Field(
        None, description='List of calculation methods this parameter applies to'
    )
    disabled_for: Optional[List[str]] = Field(
        None, description='List of calculation methods where this parameter is disabled'
    )
    description: Optional[str] = Field(
        None, description='Human-readable description of the constraint'
    )


class ParameterConstraints(RootModel[Optional[Dict[str, ParameterConstraint]]]):
    """
    Constraints for all calculation parameters (e.g., ncas, optimize_geometry)
    """

    root: Optional[Dict[str, ParameterConstraint]] = None


class Timezone(Enum):
    """
    Display timezone for timestamps in chat history and calculation history
    """

    UTC = 'UTC'
    Asia_Tokyo = 'Asia/Tokyo'
    Asia_Shanghai = 'Asia/Shanghai'
    Asia_Seoul = 'Asia/Seoul'
    Asia_Singapore = 'Asia/Singapore'
    Asia_Kolkata = 'Asia/Kolkata'
    Australia_Sydney = 'Australia/Sydney'
    Europe_London = 'Europe/London'
    Europe_Paris = 'Europe/Paris'
    Europe_Berlin = 'Europe/Berlin'
    America_New_York = 'America/New_York'
    America_Chicago = 'America/Chicago'
    America_Denver = 'America/Denver'
    America_Los_Angeles = 'America/Los_Angeles'


class AppSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_parallel_instances: int = Field(
        ...,
        description='Maximum number of parallel calculation instances',
        examples=[4],
        ge=1,
        le=32,
    )
    max_cpu_utilization_percent: float = Field(
        ...,
        description='Maximum CPU utilization percentage for the system',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    max_memory_utilization_percent: float = Field(
        ...,
        description='Maximum memory utilization percentage for the system',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    gpu_acceleration_enabled: Optional[bool] = Field(
        False,
        description='Whether GPU acceleration is enabled for calculations (Linux only)',
        examples=[False],
    )
    system_total_cores: int = Field(
        ...,
        description='Total number of CPU cores in the system (auto-detected)',
        examples=[8],
        ge=1,
    )
    system_total_memory_mb: int = Field(
        ...,
        description='Total system memory in MB (auto-detected)',
        examples=[16384],
        ge=1,
    )
    calculations_directory: str = Field(
        ...,
        description='Directory path where calculation data is stored',
        examples=['/Users/username/PySCF_calculations'],
    )
    timezone: Timezone = Field(
        ...,
        description='Display timezone for timestamps in chat history and calculation history',
        examples=['UTC'],
    )
    gemini_api_key: Optional[str] = Field(
        None,
        description='Google Gemini API key required for AI agent chat functionality.',
        examples=[None],
    )
    research_email: Optional[str] = Field(
        None,
        description='Email address for academic research API access (PubMed, OpenAlex). Required by some APIs for polite pool access.',
        examples=['pyscf-research-agent@example.com'],
    )


class AppSettingsResponse(BaseModel):
    max_parallel_instances: int = Field(
        ...,
        description='Maximum number of parallel calculation instances',
        examples=[4],
        ge=1,
        le=32,
    )
    max_cpu_utilization_percent: float = Field(
        ...,
        description='Maximum CPU utilization percentage for the system',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    max_memory_utilization_percent: float = Field(
        ...,
        description='Maximum memory utilization percentage for the system',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    gpu_acceleration_enabled: Optional[bool] = Field(
        False,
        description='Whether GPU acceleration is enabled for calculations (Linux only)',
        examples=[False],
    )
    system_total_cores: int = Field(
        ...,
        description='Total number of CPU cores in the system (auto-detected)',
        examples=[8],
        ge=1,
    )
    system_total_memory_mb: int = Field(
        ...,
        description='Total system memory in MB (auto-detected)',
        examples=[16384],
        ge=1,
    )
    calculations_directory: str = Field(
        ...,
        description='Directory path where calculation data is stored',
        examples=['/Users/username/PySCF_calculations'],
    )
    timezone: Timezone = Field(
        ...,
        description='Display timezone for timestamps in chat history and calculation history',
        examples=['UTC'],
    )
    gemini_api_key_configured: bool = Field(
        ...,
        description='Whether a non-empty Gemini API key is stored. The actual key value is never returned.',
        examples=[False],
    )
    gemini_api_key: Optional[str] = Field(
        None,
        description='Always returned as empty string. The real key is never exposed via GET.',
        examples=[''],
    )
    research_email: Optional[str] = Field(
        None,
        description='Email address for academic research API access (PubMed, OpenAlex). Required by some APIs for polite pool access.',
        examples=['pyscf-research-agent@example.com'],
    )


class Data13(BaseModel):
    settings: AppSettingsResponse


class SettingsResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data13


class SettingsUpdateRequest(RootModel[AppSettings]):
    root: AppSettings


class ErrorResponse(BaseModel):
    success: bool = Field(..., examples=[False])
    error: str = Field(..., description='Error message')


class SystemResourceInfo(BaseModel):
    total_cpu_cores: int = Field(
        ..., description='Total number of CPU cores', examples=[8], ge=1
    )
    total_memory_mb: int = Field(
        ..., description='Total system memory in MB', examples=[16384], ge=1
    )
    available_memory_mb: int = Field(
        ..., description='Available system memory in MB', examples=[8192], ge=0
    )
    cpu_usage_percent: float = Field(
        ...,
        description='Current CPU usage percentage',
        examples=[25.5],
        ge=0.0,
        le=100.0,
    )
    memory_usage_percent: float = Field(
        ...,
        description='Current memory usage percentage',
        examples=[50.2],
        ge=0.0,
        le=100.0,
    )
    timestamp: AwareDatetime = Field(
        ..., description='Timestamp when the resource info was collected'
    )


class ResourceConstraints(BaseModel):
    max_cpu_utilization_percent: float = Field(
        ...,
        description='Maximum CPU utilization percentage',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    max_memory_utilization_percent: float = Field(
        ...,
        description='Maximum memory utilization percentage',
        examples=[95.0],
        ge=10.0,
        le=100.0,
    )
    max_allowed_cpu_cores: int = Field(
        ...,
        description='Maximum allowed CPU cores for calculations',
        examples=[6],
        ge=1,
    )
    max_allowed_memory_mb: int = Field(
        ...,
        description='Maximum allowed memory in MB for calculations',
        examples=[13107],
        ge=1,
    )


class AllocatedResources(BaseModel):
    total_allocated_cpu_cores: int = Field(
        ...,
        description='Total CPU cores currently allocated to calculations',
        examples=[4],
        ge=0,
    )
    total_allocated_memory_mb: int = Field(
        ...,
        description='Total memory in MB currently allocated to calculations',
        examples=[8192],
        ge=0,
    )
    available_cpu_cores: int = Field(
        ..., description='Available CPU cores for new calculations', examples=[2], ge=0
    )
    available_memory_mb: int = Field(
        ...,
        description='Available memory in MB for new calculations',
        examples=[4915],
        ge=0,
    )
    active_calculations_count: int = Field(
        ..., description='Number of active calculations', examples=[2], ge=0
    )


class SystemResourceSummary(BaseModel):
    system_info: SystemResourceInfo
    resource_constraints: ResourceConstraints
    allocated_resources: AllocatedResources


class SystemResourceResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: SystemResourceSummary


class Gpu4PyscfStatus(BaseModel):
    is_linux: bool = Field(
        ..., description='Whether the application is running on Linux'
    )
    cuda_detected: bool = Field(
        ..., description='Whether CUDA Toolkit was detected via nvcc'
    )
    cuda_version: Optional[str] = Field(
        None,
        description='Detected CUDA Toolkit version (major.minor)',
        examples=['12.4'],
    )
    cuda_major: Optional[int] = Field(
        None, description='Detected CUDA major version', examples=[12]
    )
    cuda_minor: Optional[int] = Field(
        None, description='Detected CUDA minor version', examples=[4]
    )
    cuda_supported: bool = Field(
        ..., description='Whether detected CUDA version is supported by GPU4PySCF'
    )
    cuda_detection_message: Optional[str] = Field(
        None, description='Additional message for CUDA detection failures or warnings'
    )
    recommended_gpu4pyscf_package: Optional[str] = Field(
        None,
        description='Recommended GPU4PySCF package for the detected CUDA version',
        examples=['gpu4pyscf-cuda12x'],
    )
    recommended_cutensor_package: Optional[str] = Field(
        None,
        description='Recommended cuTENSOR package for the detected CUDA version',
        examples=['cutensor-cu12'],
    )
    gpu4pyscf_installed: bool = Field(..., description='Whether GPU4PySCF is installed')
    gpu4pyscf_version: Optional[str] = Field(
        None, description='Installed GPU4PySCF version'
    )
    cutensor_installed: bool = Field(..., description='Whether cuTENSOR is installed')
    cutensor_version: Optional[str] = Field(
        None, description='Installed cuTENSOR version'
    )


class Gpu4PyscfInstallRequest(BaseModel):
    include_cutensor: Optional[bool] = Field(
        True, description='Whether to install cuTENSOR alongside GPU4PySCF'
    )
    force_reinstall: Optional[bool] = Field(
        False, description='Force reinstall of GPU4PySCF and cuTENSOR packages'
    )
    confirm_install: Optional[bool] = Field(
        False,
        description='Must be true to confirm the installation and allow environment mutation. Prevents accidental installs.',
    )


class Gpu4PyscfInstallResult(BaseModel):
    status: Gpu4PyscfStatus
    packages: List[str]
    used_user_site: bool = Field(
        ..., description='Whether pip installed into the user site-packages directory'
    )
    pip_stdout: str = Field(..., description='Tail of pip stdout output')
    pip_stderr: str = Field(..., description='Tail of pip stderr output')


class Gpu4PyscfStatusResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Gpu4PyscfStatus


class Gpu4PyscfInstallResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Gpu4PyscfInstallResult


class AtomDisplacement(BaseModel):
    atom_index: int = Field(
        ..., description='Zero-based index of the atom', examples=[0]
    )
    element: str = Field(..., description='Element symbol', examples=['C'])
    x: float = Field(
        ..., description='X coordinate of the atom (Angstrom)', examples=[0.0]
    )
    y: float = Field(
        ..., description='Y coordinate of the atom (Angstrom)', examples=[0.0]
    )
    z: float = Field(
        ..., description='Z coordinate of the atom (Angstrom)', examples=[0.0]
    )
    dx: float = Field(
        ..., description='X component of displacement vector', examples=[0.123]
    )
    dy: float = Field(
        ..., description='Y component of displacement vector', examples=[-0.045]
    )
    dz: float = Field(
        ..., description='Z component of displacement vector', examples=[0.078]
    )


class IRPeak(BaseModel):
    frequency_cm: float = Field(
        ...,
        description='Peak frequency after scale factor correction (cm⁻¹)',
        examples=[1654.2],
    )
    intensity: float = Field(
        ..., description='Peak intensity (arbitrary units)', examples=[120.5]
    )
    original_frequency_cm: float = Field(
        ...,
        description='Original calculated frequency before scale factor correction (cm⁻¹)',
        examples=[1723.1],
    )
    mode_displacements: Optional[List[AtomDisplacement]] = Field(
        None, description='Vibrational mode displacement vectors for 3D visualization'
    )


class IRSpectrumMetadata(BaseModel):
    method: str = Field(
        ..., description='Computational method used', examples=['B3LYP']
    )
    basis_set: str = Field(..., description='Basis set used', examples=['6-31G*'])
    scale_factor: float = Field(
        ..., description='Scale factor applied to frequencies', examples=[0.96]
    )
    scale_message: str = Field(
        ...,
        description='Information about the scale factor source',
        examples=['Exact match found'],
    )
    broadening_fwhm_cm: float = Field(
        ...,
        description='Full width at half maximum for Lorentzian broadening (cm⁻¹)',
        examples=[100.0],
    )
    frequency_range_cm: List[float] = Field(
        ...,
        description='Frequency range for the spectrum [min, max] (cm⁻¹)',
        examples=[[400.0, 4000.0]],
        max_length=2,
        min_length=2,
    )
    num_peaks_total: int = Field(
        ..., description='Total number of calculated frequencies', examples=[24]
    )
    num_peaks_in_range: int = Field(
        ..., description='Number of peaks within the specified range', examples=[18]
    )
    num_points: int = Field(
        ..., description='Number of points in the spectrum', examples=[3000]
    )


class IRGenerationInfo(BaseModel):
    broadening_fwhm_cm: float = Field(
        ...,
        description='Full width at half maximum used for broadening (cm⁻¹)',
        examples=[100.0],
    )
    frequency_range_cm: List[float] = Field(
        ...,
        description='Frequency range used [min, max] (cm⁻¹)',
        examples=[[400.0, 4000.0]],
        max_length=2,
        min_length=2,
    )
    peaks_marked: bool = Field(
        ...,
        description='Whether individual peaks were marked in the plot',
        examples=[True],
    )
    generated_at: AwareDatetime = Field(
        ...,
        description='ISO timestamp when the spectrum was generated',
        examples=['2024-01-01T12:00:00.000Z'],
    )


class NaturalOrbitalAnalysis(BaseModel):
    enabled: Optional[bool] = Field(
        None, description='Whether natural orbital analysis was performed'
    )
    occupation_numbers: Optional[List[float]] = Field(
        None, description='Natural orbital occupation numbers'
    )
    strongly_occupied_count: Optional[int] = Field(
        None, description='Number of strongly occupied orbitals (occupation > 1.5)'
    )
    weakly_occupied_count: Optional[int] = Field(
        None, description='Number of weakly occupied orbitals (0.1 < occupation <= 1.5)'
    )
    virtual_count: Optional[int] = Field(
        None, description='Number of virtual orbitals (occupation <= 0.1)'
    )
    total_orbitals: Optional[int] = Field(
        None, description='Total number of active space orbitals analyzed'
    )
    total_active_electrons: Optional[float] = Field(
        None, description='Total number of electrons in active space'
    )
    effective_electron_pairs: Optional[float] = Field(
        None, description='Effective number of electron pairs'
    )
    effective_unpaired_electrons: Optional[float] = Field(
        None, description='Effective number of unpaired electrons'
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class MajorConfiguration(BaseModel):
    configuration_index: Optional[int] = Field(
        None, description='Index of the configuration'
    )
    coefficient: Optional[float] = Field(None, description='CI coefficient value')
    contribution_percent: Optional[float] = Field(
        None, description='Percentage contribution to the wavefunction'
    )
    cumulative_percent: Optional[float] = Field(
        None, description='Cumulative percentage contribution'
    )


class CICoefficientAnalysis(BaseModel):
    available: Optional[bool] = Field(
        None, description='Whether CI coefficient analysis is available'
    )
    total_configurations: Optional[int] = Field(
        None, description='Total number of configurations'
    )
    major_configurations: Optional[List[MajorConfiguration]] = Field(
        None, description='Major configurations with significant contributions'
    )
    leading_coefficient: Optional[float] = Field(
        None, description='Leading CI coefficient (largest magnitude)'
    )
    leading_contribution_percent: Optional[float] = Field(
        None, description='Percentage contribution of the leading configuration'
    )
    multiconfigurational_character: Optional[float] = Field(
        None,
        description='Percentage multiconfigurational character (100 - leading contribution)',
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class AtomicSpinDensity(BaseModel):
    atom_index: Optional[int] = Field(None, description='0-based index of the atom')
    element: Optional[str] = Field(None, description='Element symbol')
    spin_density: Optional[float] = Field(
        None, description='Atomic spin density (alpha - beta electrons)'
    )
    abs_spin_density: Optional[float] = Field(
        None, description='Absolute value of atomic spin density'
    )


class MullikenSpinAnalysis(BaseModel):
    available: Optional[bool] = Field(
        None, description='Whether Mulliken spin analysis is available'
    )
    atomic_spin_densities: Optional[List[AtomicSpinDensity]] = Field(
        None, description='Spin density for each atom'
    )
    total_spin_density: Optional[float] = Field(
        None, description='Total spin density of the molecule'
    )
    total_absolute_spin_density: Optional[float] = Field(
        None, description='Sum of absolute atomic spin densities'
    )
    expected_spin: Optional[float] = Field(
        None, description='Expected spin (2S) from molecular parameters'
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class ScfOrbitalType(Enum):
    """
    Type of dominant SCF orbital
    """

    occupied = 'occupied'
    partially_occupied = 'partially_occupied'
    virtual = 'virtual'
    unknown = 'unknown'


class ActiveOrbitalAnalysi(BaseModel):
    active_orbital_index: Optional[int] = Field(
        None, description='Index of active space orbital'
    )
    dominant_scf_orbital: Optional[int] = Field(
        None, description='Index of dominant SCF orbital'
    )
    max_overlap: Optional[float] = Field(
        None, description='Maximum overlap with SCF orbitals'
    )
    scf_orbital_type: Optional[ScfOrbitalType] = Field(
        None, description='Type of dominant SCF orbital'
    )


class OrbitalTransformationCharacter(Enum):
    """
    Character of orbital transformation
    """

    minimal = 'minimal'
    significant = 'significant'


class OrbitalOverlapAnalysis(BaseModel):
    available: Optional[bool] = Field(
        None, description='Whether orbital overlap analysis is available'
    )
    active_space_orbitals: Optional[int] = Field(
        None, description='Number of active space orbitals analyzed'
    )
    active_orbital_analysis: Optional[List[ActiveOrbitalAnalysi]] = Field(
        None, description='Analysis of each active space orbital'
    )
    average_max_overlap: Optional[float] = Field(
        None, description='Average maximum overlap across active orbitals'
    )
    orbital_transformation_character: Optional[OrbitalTransformationCharacter] = Field(
        None, description='Character of orbital transformation'
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class RotationExtent(Enum):
    """
    Extent of orbital rotation during CASSCF optimization
    """

    minimal = 'minimal'
    moderate = 'moderate'
    significant = 'significant'


class OrbitalRotationAnalysis(BaseModel):
    available: Optional[bool] = Field(
        None, description='Whether orbital rotation analysis is available'
    )
    core_orbital_rotation_magnitude: Optional[float] = Field(
        None, description='Maximum rotation magnitude for core orbitals'
    )
    active_orbital_rotation_magnitude: Optional[float] = Field(
        None, description='Maximum rotation magnitude for active orbitals'
    )
    virtual_orbital_rotation_magnitude: Optional[float] = Field(
        None, description='Maximum rotation magnitude for virtual orbitals'
    )
    overall_rotation_magnitude: Optional[float] = Field(
        None, description='Overall maximum rotation magnitude'
    )
    rotation_extent: Optional[RotationExtent] = Field(
        None, description='Extent of orbital rotation during CASSCF optimization'
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class Source(Enum):
    """
    Source of CI analysis (from kernel return value)
    """

    kernel_return = 'kernel_return'


class WavefunctionCharacter(Enum):
    """
    Overall character of the wavefunction
    """

    single_configuration = 'single_configuration'
    few_configuration = 'few_configuration'
    multiconfigurational = 'multiconfigurational'


class EnhancedCIAnalysis(BaseModel):
    source: Optional[Source] = Field(
        None, description='Source of CI analysis (from kernel return value)'
    )
    available: Optional[bool] = Field(
        None, description='Whether enhanced CI analysis is available'
    )
    total_coefficients: Optional[int] = Field(
        None, description='Total number of CI coefficients'
    )
    ci_vector_shape: Optional[str] = Field(
        None, description='Shape of the CI coefficient vector/matrix'
    )
    major_configurations: Optional[List[MajorConfiguration]] = Field(
        None, description='Major configurations with >0.5% contribution'
    )
    leading_coefficient: Optional[float] = Field(
        None, description='Leading CI coefficient (largest magnitude)'
    )
    leading_contribution_percent: Optional[float] = Field(
        None, description='Percentage contribution of the leading configuration'
    )
    multiconfigurational_character: Optional[float] = Field(
        None,
        description='Multiconfigurational character (100 - leading contribution %)',
    )
    effective_configurations: Optional[int] = Field(
        None, description='Number of configurations with significant contribution'
    )
    wavefunction_entropy: Optional[float] = Field(
        None,
        description='Entropy measure of wavefunction multiconfigurational character',
    )
    wavefunction_character: Optional[WavefunctionCharacter] = Field(
        None, description='Overall character of the wavefunction'
    )
    normalization: Optional[float] = Field(
        None, description='Normalization of the CI vector'
    )
    reason: Optional[str] = Field(
        None, description='Reason if analysis was not performed'
    )
    error: Optional[str] = Field(None, description='Error message if analysis failed')


class Role(Enum):
    user = 'user'
    model = 'model'


class Part(BaseModel):
    text: Optional[str] = Field(None, max_length=10000)


class HistoryItem(BaseModel):
    role: Optional[Role] = None
    parts: Optional[List[Part]] = Field(
        None,
        description='Content parts within a single history item. A normal message contains 1 part; the cap of 100 is intentionally generous for legitimate multi-part use while preventing DoS amplification through unbounded iteration.',
        max_length=100,
    )


class AgentChatRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: str = Field(..., description='New message from the user', max_length=10000)
    history: List[HistoryItem] = Field(
        ..., description='Previous conversation history', max_length=200
    )
    session_id: Optional[str] = Field(
        None, description='Optional chat session ID for persisting conversation history'
    )


class Data14(BaseModel):
    reply: str = Field(..., description='Response message from the AI agent')


class AgentChatResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data14


class Role1(Enum):
    """
    Message sender role
    """

    user = 'user'
    model = 'model'


class ChatMessage(BaseModel):
    id: str = Field(
        ...,
        description='Unique message ID (UUID)',
        examples=['msg_550e8400-e29b-41d4-a716-446655440000'],
    )
    session_id: str = Field(
        ...,
        description='Associated chat session ID',
        examples=['session_550e8400-e29b-41d4-a716-446655440000'],
    )
    role: Role1 = Field(..., description='Message sender role')
    content: str = Field(..., description='Message content')
    created_at: AwareDatetime = Field(..., description='Message creation timestamp')


class ChatSession(BaseModel):
    id: str = Field(
        ...,
        description='Unique session ID (UUID)',
        examples=['session_550e8400-e29b-41d4-a716-446655440000'],
    )
    name: str = Field(
        ..., description='Session name/title', examples=['水分子のDFT計算']
    )
    created_at: AwareDatetime = Field(..., description='Session creation timestamp')
    updated_at: AwareDatetime = Field(..., description='Last update timestamp')


class ChatSessionSummary(BaseModel):
    id: str = Field(..., description='Unique session ID')
    name: str = Field(..., description='Session name/title')
    message_count: int = Field(
        ..., description='Number of messages in this session', ge=0
    )
    created_at: AwareDatetime = Field(..., description='Session creation timestamp')
    updated_at: AwareDatetime = Field(..., description='Last update timestamp')


class ChatSessionDetail(BaseModel):
    session: ChatSession
    messages: List[ChatMessage] = Field(
        ..., description='All messages in this session, ordered by creation time'
    )


class CreateChatSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = Field(
        '新しいチャット', description='Session name/title', max_length=200, min_length=1
    )


class UpdateChatSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='Updated session name', max_length=200, min_length=1
    )


class Data15(BaseModel):
    sessions: List[ChatSessionSummary] = Field(..., description='List of chat sessions')
    total_count: int = Field(..., description='Total number of sessions', ge=0)


class ChatHistoryListResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data15


class Data16(BaseModel):
    session: ChatSession


class ChatSessionResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data16


class ChatSessionDetailResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: ChatSessionDetail


class Data17(BaseModel):
    message: str = Field(..., description='Deletion confirmation message')
    deleted_id: str = Field(..., description='ID of the deleted session')


class ChatSessionDeleteResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data17


class Data18(BaseModel):
    message: str = Field(
        ...,
        description='Confirmation message',
        examples=[
            'Pause request accepted. Calculation will pause after current iteration.'
        ],
    )
    calculation_id: str = Field(..., description='ID of the calculation being paused')


class PauseCalculationResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data18


class CalculationResults(BaseModel):
    scf_energy: Optional[float] = Field(None, description='SCF energy result')
    converged: Optional[bool] = Field(None, description='Whether calculation converged')
    gpu_enabled: Optional[bool] = Field(
        None, description='Whether GPU acceleration was used for this calculation'
    )
    homo_index: Optional[int] = Field(None, description='HOMO orbital index')
    lumo_index: Optional[int] = Field(None, description='LUMO orbital index')
    num_occupied_orbitals: Optional[int] = Field(
        None, description='Number of occupied orbitals'
    )
    num_virtual_orbitals: Optional[int] = Field(
        None, description='Number of virtual orbitals'
    )
    checkpoint_file: Optional[str] = Field(None, description='Path to checkpoint file')
    checkpoint_exists: Optional[bool] = Field(
        None, description='Whether checkpoint file exists'
    )
    working_directory: Optional[str] = Field(None, description='Working directory path')
    optimized_geometry: Optional[str] = Field(
        None, description='Optimized molecular geometry'
    )
    basis: Optional[str] = Field(None, description='Basis set used')
    xc_functional: Optional[str] = Field(
        None, description='Exchange-correlation functional used'
    )
    charge: Optional[float] = Field(None, description='Molecular charge')
    spin: Optional[int] = Field(
        None, description='Spin (2S), number of unpaired electrons'
    )
    max_cycle: Optional[int] = Field(None, description='Maximum SCF cycles')
    atom_count: Optional[int] = Field(None, description='Number of atoms')
    error: Optional[str] = Field(
        None, description='Error message if calculation failed'
    )
    dipole_moment_x_debye: Optional[float] = Field(
        None, description='Dipole moment X component in Debye'
    )
    dipole_moment_y_debye: Optional[float] = Field(
        None, description='Dipole moment Y component in Debye'
    )
    dipole_moment_z_debye: Optional[float] = Field(
        None, description='Dipole moment Z component in Debye'
    )
    dipole_moment_total_debye: Optional[float] = Field(
        None, description='Total dipole moment magnitude in Debye'
    )
    dipole_moment_x_au: Optional[float] = Field(
        None, description='Dipole moment X component in atomic units'
    )
    dipole_moment_y_au: Optional[float] = Field(
        None, description='Dipole moment Y component in atomic units'
    )
    dipole_moment_z_au: Optional[float] = Field(
        None, description='Dipole moment Z component in atomic units'
    )
    dipole_moment_total_au: Optional[float] = Field(
        None, description='Total dipole moment magnitude in atomic units'
    )
    homo_energy_hartree: Optional[float] = Field(
        None, description='HOMO orbital energy in hartree'
    )
    homo_energy_ev: Optional[float] = Field(
        None, description='HOMO orbital energy in eV'
    )
    lumo_energy_hartree: Optional[float] = Field(
        None, description='LUMO orbital energy in hartree'
    )
    lumo_energy_ev: Optional[float] = Field(
        None, description='LUMO orbital energy in eV'
    )
    homo_lumo_gap_hartree: Optional[float] = Field(
        None, description='HOMO-LUMO energy gap in hartree'
    )
    homo_lumo_gap_ev: Optional[float] = Field(
        None, description='HOMO-LUMO energy gap in eV'
    )
    nuclear_repulsion_energy: Optional[float] = Field(
        None, description='Nuclear repulsion energy in hartree'
    )
    electronic_energy: Optional[float] = Field(
        None, description='Electronic energy in hartree'
    )
    num_basis_functions: Optional[int] = Field(
        None, description='Total number of basis functions'
    )
    num_primitive_gaussians: Optional[int] = Field(
        None, description='Total number of primitive Gaussian functions'
    )
    total_electrons: Optional[int] = Field(
        None, description='Total number of electrons in the molecule'
    )
    resolved_auxiliary_basis: Optional[str] = Field(
        None, description='Actual auxiliary basis selected by PySCF for density fitting'
    )
    mp2_same_spin_correlation: Optional[float] = Field(
        None, description='MP2 same-spin correlation energy in hartree'
    )
    mp2_opposite_spin_correlation: Optional[float] = Field(
        None, description='MP2 opposite-spin correlation energy in hartree'
    )
    ccsd_t1_diagnostic: Optional[float] = Field(
        None,
        description='CCSD T1 diagnostic (>0.02 suggests multi-reference character)',
    )
    ccsd_d1_diagnostic: Optional[float] = Field(
        None,
        description='CCSD D1 diagnostic (alternative diagnostic based on density matrix)',
    )
    ccsd_d2_diagnostic: Optional[float] = Field(
        None, description='CCSD D2 diagnostic (diagnostic based on T2 amplitudes)'
    )
    scf_iterations: Optional[int] = Field(
        None, description='Number of SCF iterations performed'
    )
    final_energy_change: Optional[float] = Field(
        None, description='Final energy change in SCF convergence'
    )
    final_density_change: Optional[float] = Field(
        None, description='Final density matrix change in SCF convergence'
    )
    excitation_energies: Optional[List[float]] = Field(
        None, description='Excitation energies in eV (TDDFT only)'
    )
    excitation_wavelengths: Optional[List[float]] = Field(
        None, description='Excitation wavelengths in nm (TDDFT only)'
    )
    oscillator_strengths: Optional[List[float]] = Field(
        None, description='Oscillator strengths for transitions (TDDFT only)'
    )
    transition_dipoles: Optional[List[TransitionDipole]] = Field(
        None, description='Transition dipole moments (TDDFT only)'
    )
    major_transitions: Optional[List[MajorTransition]] = Field(
        None, description='Major orbital transitions (TDDFT only)'
    )
    nto_analysis: Optional[List[NtoAnalysi]] = Field(
        None, description='Natural Transition Orbital analysis results (TDDFT only)'
    )
    mulliken_charges: Optional[List[MullikenCharge]] = Field(
        None, description='Mulliken population analysis charges for each atom'
    )
    frequency_analysis_performed: Optional[bool] = Field(
        None, description='Whether vibrational frequency analysis was performed'
    )
    vibrational_frequencies: Optional[List[float]] = Field(
        None,
        description='Vibrational frequencies in cm⁻¹ (positive frequencies only, excluding low-frequency modes)',
    )
    imaginary_frequencies_count: Optional[int] = Field(
        None,
        description='Number of imaginary frequencies (negative eigenvalues) - indicates optimization quality',
    )
    zero_point_energy: Optional[float] = Field(
        None, description='Zero-point vibrational energy in Hartree'
    )
    thermal_energy_298K: Optional[float] = Field(
        None, description='Thermal energy at 298.15 K in Hartree'
    )
    entropy_298K: Optional[float] = Field(
        None, description='Entropy at 298.15 K in Hartree/K'
    )
    gibbs_free_energy_298K: Optional[float] = Field(
        None, description='Gibbs free energy at 298.15 K in Hartree'
    )
    heat_capacity_298K: Optional[float] = Field(
        None, description='Heat capacity at 298.15 K in Hartree/K'
    )
    casci_energy: Optional[float] = Field(
        None, description='CASCI energy in Hartree (CASCI only)'
    )
    casscf_energy: Optional[float] = Field(
        None, description='CASSCF energy in Hartree (CASSCF only)'
    )
    correlation_energy: Optional[float] = Field(
        None, description='Correlation energy (CASCI/CASSCF - SCF) in Hartree'
    )
    macro_iterations: Optional[int] = Field(
        None, description='Number of CASSCF macro iterations performed'
    )
    natural_orbital_analysis: Optional[NaturalOrbitalAnalysis] = Field(
        None, description='Natural orbital analysis results (CASCI/CASSCF)'
    )
    ci_coefficient_analysis: Optional[CICoefficientAnalysis] = Field(
        None, description='CI coefficient analysis results (CASCI/CASSCF)'
    )
    mulliken_spin_analysis: Optional[MullikenSpinAnalysis] = Field(
        None,
        description='Mulliken atomic spin density analysis (CASCI/CASSCF open-shell)',
    )
    orbital_overlap_analysis: Optional[OrbitalOverlapAnalysis] = Field(
        None,
        description='Orbital overlap analysis between SCF and CASCI/CASSCF orbitals',
    )
    orbital_rotation_analysis: Optional[OrbitalRotationAnalysis] = Field(
        None,
        description='Orbital rotation analysis during CASSCF optimization (CASSCF only)',
    )
    kernel_return_info: Optional[KernelReturnInfo] = Field(
        None, description='Information about kernel() return value structure'
    )
    ci_coefficients_available: Optional[bool] = Field(
        None, description='Whether CI coefficients are available from kernel() return'
    )
    enhanced_ci_analysis: Optional[EnhancedCIAnalysis] = Field(
        None, description='Enhanced CI coefficient analysis from kernel() return'
    )


class CalculationInstance(BaseModel):
    id: str = Field(..., description='Unique calculation ID')
    name: str = Field(..., description='Display name for the calculation')
    status: CalculationStatus
    createdAt: AwareDatetime = Field(..., description='Creation timestamp')
    updatedAt: AwareDatetime = Field(..., description='Last update timestamp')
    parameters: CalculationParameters
    results: Optional[CalculationResults] = None
    workingDirectory: Optional[str] = Field(
        None, description='Path to calculation files'
    )
    error: Optional[str] = Field(None, description='Error details if status is error')
    waitingReason: Optional[str] = Field(
        None, description='Reason why calculation is waiting (if status is waiting)'
    )
    canResume: Optional[bool] = Field(
        None, description='Whether this calculation can be resumed from a paused state'
    )
    pausedAt: Optional[AwareDatetime] = Field(
        None, description='Timestamp when calculation was paused'
    )
    resumeInfo: Optional[ResumeInfo] = Field(
        None, description='Information about the paused state for resuming'
    )


class CalculationUpdateStreamPayload(BaseModel):
    calculation: CalculationInstance


class Data3(BaseModel):
    calculation: CalculationInstance


class StartCalculationResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data3


class Data6(BaseModel):
    calculation: CalculationInstance
    files: Files


class CalculationDetailsResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data6


class SupportedParametersData(BaseModel):
    calculation_methods: List[str] = Field(
        ..., description='Supported quantum calculation methods'
    )
    basis_functions: Dict[str, List[str]] = Field(
        ...,
        description='Supported basis functions grouped by category (e.g., Minimal, Pople Style, etc.)',
    )
    auxiliary_basis_functions: Dict[str, List[str]] = Field(
        ...,
        description='Supported auxiliary basis sets for density fitting, grouped by category',
    )
    exchange_correlation: Dict[str, List[str]] = Field(
        ...,
        description='Supported exchange-correlation functionals grouped by category (e.g., Hybrid, GGA, etc.)',
    )
    solvent_methods: List[str] = Field(
        ..., description='Supported solvent effect methods'
    )
    solvents: Dict[str, List[SolventOption]] = Field(
        ...,
        description='Supported solvents grouped by category (e.g., Highly Polar, Protic, etc.)',
    )
    tddft_methods: List[str] = Field(
        ..., description='Supported TDDFT calculation methods'
    )
    method_defaults: MethodDefaultValues = Field(
        ..., description='Default parameter values for each calculation method'
    )
    parameter_constraints: ParameterConstraints = Field(
        ..., description='Constraints and validation rules for calculation parameters'
    )


class SupportedParametersResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: SupportedParametersData


class IRSpectrumDetails(BaseModel):
    x_axis: List[float] = Field(
        ...,
        description='Wavenumber values (cm⁻¹) for the x-axis',
        examples=[[400.0, 401.0, 402.0]],
    )
    y_axis: List[float] = Field(
        ...,
        description='Intensity values for the y-axis (arbitrary units)',
        examples=[[0.0, 0.1, 0.05]],
    )
    peaks: List[IRPeak] = Field(..., description='Individual peaks in the spectrum')
    metadata: IRSpectrumMetadata


class Data19(BaseModel):
    message: str = Field(
        ...,
        description='Confirmation message',
        examples=['Calculation resumed from checkpoint'],
    )
    calculation: CalculationInstance


class ResumeCalculationResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data19


class IRSpectrumData(BaseModel):
    calculation_id: str = Field(
        ...,
        description='Unique calculation ID',
        examples=['calc_20240101_120000_abcd1234'],
    )
    spectrum: IRSpectrumDetails
    generation_info: IRGenerationInfo


class IRSpectrumResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: IRSpectrumData
