# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-08-19T07:44:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AwareDatetime, BaseModel, Field


class SearchType(Enum):
    """
    Type of PubChem search
    """

    name = 'name'
    cid = 'cid'
    formula = 'formula'


class SolventMethod(Enum):
    """
    Solvent calculation method
    """

    none = 'none'
    ief_pcm = 'ief-pcm'
    c_pcm = 'c-pcm'
    cosmo = 'cosmo'
    ssvpe = 'ssvpe'
    ddcosmo = 'ddcosmo'


class CalculationMethod(Enum):
    """
    Quantum calculation method
    """

    DFT = 'DFT'
    HF = 'HF'
    MP2 = 'MP2'
    TDDFT = 'TDDFT'


class CalculationStatus(Enum):
    """
    Status of a calculation
    """

    pending = 'pending'
    running = 'running'
    completed = 'completed'
    error = 'error'


class PubChemSearchRequest(BaseModel):
    query: str = Field(..., description='Search query for PubChem', min_length=1)
    search_type: Optional[SearchType] = 'name'


class SMILESConvertRequest(BaseModel):
    smiles: str = Field(
        ..., description='SMILES string to convert to XYZ format', min_length=1
    )


class XYZValidateRequest(BaseModel):
    xyz: str = Field(..., description='XYZ string to validate', min_length=1)


class TddftMethod(Enum):
    """
    TDDFT calculation method - TDDFT or Tamm-Dancoff approximation
    """

    TDDFT = 'TDDFT'
    TDA = 'TDA'


class QuantumCalculationRequest(BaseModel):
    xyz: str = Field(..., description='XYZ molecular structure data', min_length=1)
    calculation_method: Optional[CalculationMethod] = 'DFT'
    basis_function: Optional[str] = Field(
        '6-31G(d)',
        description='Basis set for calculation (e.g., STO-3G, 6-31G(d), 6-31+G(d,p), cc-pVDZ, aug-cc-pVTZ, def2-SVP)',
    )
    exchange_correlation: Optional[str] = Field(
        'B3LYP',
        description='Exchange-correlation functional (e.g., B3LYP, PBE0, M06-2X, CAM-B3LYP, PBE, BLYP, M06, TPSS)',
    )
    charges: Optional[int] = Field(0, description='Molecular charge', ge=-10, le=10)
    spin_multiplicity: Optional[int] = Field(
        1, description='Spin multiplicity', ge=1, le=10
    )
    solvent_method: Optional[SolventMethod] = 'none'
    solvent: Optional[str] = Field(
        '-',
        description='Solvent type or custom parameters. Options include:\n- Predefined solvents: water, dimethylsulfoxide, n,n-dimethylformamide, nitromethane, methanol, ethanol, acetone, dichloroethane, dichloromethane, tetrahydrofuran, chlorobenzene, chloroform, diethylether, toluene, benzene, 1,4-dioxane, cyclohexane\n- Custom dielectric constant (numeric value > 1.0)\n',
    )
    name: Optional[str] = Field(
        'Unnamed Calculation',
        description='Name for the calculation',
        max_length=100,
        min_length=1,
    )
    cpu_cores: Optional[int] = Field(
        None, description='Number of CPU cores', ge=1, le=32
    )
    memory_mb: Optional[int] = Field(None, description='Memory in MB', ge=512, le=32768)
    tddft_nstates: Optional[int] = Field(
        10,
        description='Number of excited states to calculate (TDDFT only)',
        ge=1,
        le=50,
    )
    tddft_method: Optional[TddftMethod] = Field(
        'TDDFT',
        description='TDDFT calculation method - TDDFT or Tamm-Dancoff approximation',
    )
    tddft_analyze_nto: Optional[bool] = Field(
        False, description='Perform Natural Transition Orbital analysis (TDDFT only)'
    )


class CalculationUpdateRequest(BaseModel):
    name: str = Field(
        ...,
        description='Updated name for the calculation',
        max_length=100,
        min_length=1,
    )


class HealthResponse(BaseModel):
    status: str = Field(..., examples=['ok'])
    service: str = Field(..., examples=['pyscf-front-api'])
    version: str = Field(..., examples=['0.3.0'])


class PubChemCompoundInfo(BaseModel):
    cid: int = Field(..., description='PubChem Compound ID')
    iupac_name: str = Field(..., description='IUPAC name')
    molecular_formula: str = Field(..., description='Molecular formula')
    molecular_weight: float = Field(..., description='Molecular weight')
    synonyms: List[str] = Field(..., description='List of synonyms')


class Data(BaseModel):
    xyz: str = Field(..., description='XYZ format molecular structure')
    compound_info: PubChemCompoundInfo
    atom_count: int = Field(..., description='Number of atoms in the molecule')


class PubChemSearchResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data


class Data1(BaseModel):
    xyz: str = Field(..., description='XYZ format molecular structure')


class SMILESConvertResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data1 = Field(..., title='SMILESConvertData')


class Atom(BaseModel):
    element: str = Field(..., description='Element symbol')
    x: float = Field(..., description='X coordinate')
    y: float = Field(..., description='Y coordinate')
    z: float = Field(..., description='Z coordinate')


class Data2(BaseModel):
    """
    Validation result
    """

    valid: bool = Field(..., description='Whether the XYZ format is valid')
    error: Optional[str] = Field(None, description='Error message if validation failed')
    num_atoms: Optional[int] = Field(
        None, description='Number of atoms in the molecule (if valid)'
    )
    title: Optional[str] = Field(
        None, description='Title line from XYZ file (if valid)'
    )
    atoms: Optional[List[Atom]] = Field(
        None, description='Array of atom data (if valid)'
    )


class XYZValidateResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data2 = Field(..., description='Validation result')


class CalculationParameters(BaseModel):
    calculation_method: CalculationMethod
    basis_function: str
    exchange_correlation: str
    charges: int
    spin_multiplicity: int
    solvent_method: SolventMethod
    solvent: str
    xyz: str
    molecule_name: Optional[str] = None
    cpu_cores: Optional[int] = None
    memory_mb: Optional[int] = None
    created_at: Optional[AwareDatetime] = None
    tddft_nstates: Optional[int] = Field(
        None, description='Number of excited states (TDDFT only)'
    )
    tddft_method: Optional[str] = Field(None, description='TDDFT method used')
    tddft_analyze_nto: Optional[bool] = Field(
        None, description='Whether NTO analysis was performed'
    )


class TransitionDipole(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[float] = None


class MajorTransition(BaseModel):
    state: Optional[int] = Field(None, description='Excited state number')
    energy: Optional[float] = Field(None, description='Excitation energy in eV')
    wavelength: Optional[float] = Field(None, description='Wavelength in nm')
    oscillator_strength: Optional[float] = Field(
        None, description='Oscillator strength'
    )
    dominant_transition: Optional[str] = Field(
        None, description='Main orbital transition (e.g., HOMO -> LUMO)'
    )


class NtoPair(BaseModel):
    hole_orbital: Optional[str] = Field(
        None, description='Description of hole orbital (e.g., HOMO, HOMO-1)'
    )
    particle_orbital: Optional[str] = Field(
        None, description='Description of particle orbital (e.g., LUMO, LUMO+1)'
    )
    weight: Optional[float] = Field(None, description='NTO weight (singular value)')
    contribution: Optional[float] = Field(
        None, description='Percentage contribution to the transition'
    )
    hole_orbital_index: Optional[int] = Field(
        None, description='Index of the hole orbital'
    )
    particle_orbital_index: Optional[int] = Field(
        None, description='Index of the particle orbital'
    )


class NtoAnalysi(BaseModel):
    state: Optional[int] = Field(None, description='Excited state number (1-indexed)')
    energy: Optional[float] = Field(None, description='Excitation energy in eV')
    nto_pairs: Optional[List[NtoPair]] = Field(
        None, description='NTO orbital pairs for this excited state'
    )
    total_nto_pairs: Optional[int] = Field(
        None, description='Total number of NTO pairs analyzed'
    )


class CalculationResults(BaseModel):
    scf_energy: Optional[float] = Field(None, description='SCF energy result')
    converged: Optional[bool] = Field(None, description='Whether calculation converged')
    homo_index: Optional[int] = Field(None, description='HOMO orbital index')
    lumo_index: Optional[int] = Field(None, description='LUMO orbital index')
    num_occupied_orbitals: Optional[int] = Field(
        None, description='Number of occupied orbitals'
    )
    num_virtual_orbitals: Optional[int] = Field(
        None, description='Number of virtual orbitals'
    )
    checkpoint_file: Optional[str] = Field(None, description='Path to checkpoint file')
    checkpoint_exists: Optional[bool] = Field(
        None, description='Whether checkpoint file exists'
    )
    working_directory: Optional[str] = Field(None, description='Working directory path')
    optimized_geometry: Optional[str] = Field(
        None, description='Optimized molecular geometry'
    )
    basis: Optional[str] = Field(None, description='Basis set used')
    xc_functional: Optional[str] = Field(
        None, description='Exchange-correlation functional used'
    )
    charge: Optional[float] = Field(None, description='Molecular charge')
    spin_multiplicity: Optional[int] = Field(None, description='Spin multiplicity')
    max_cycle: Optional[int] = Field(None, description='Maximum SCF cycles')
    atom_count: Optional[int] = Field(None, description='Number of atoms')
    error: Optional[str] = Field(
        None, description='Error message if calculation failed'
    )
    excitation_energies: Optional[List[float]] = Field(
        None, description='Excitation energies in eV (TDDFT only)'
    )
    excitation_wavelengths: Optional[List[float]] = Field(
        None, description='Excitation wavelengths in nm (TDDFT only)'
    )
    oscillator_strengths: Optional[List[float]] = Field(
        None, description='Oscillator strengths for transitions (TDDFT only)'
    )
    transition_dipoles: Optional[List[TransitionDipole]] = Field(
        None, description='Transition dipole moments (TDDFT only)'
    )
    major_transitions: Optional[List[MajorTransition]] = Field(
        None, description='Major orbital transitions (TDDFT only)'
    )
    nto_analysis: Optional[List[NtoAnalysi]] = Field(
        None, description='Natural Transition Orbital analysis results (TDDFT only)'
    )


class CalculationInstance(BaseModel):
    id: str = Field(..., description='Unique calculation ID')
    name: str = Field(..., description='Display name for the calculation')
    status: CalculationStatus
    createdAt: AwareDatetime = Field(..., description='Creation timestamp')
    updatedAt: AwareDatetime = Field(..., description='Last update timestamp')
    parameters: CalculationParameters
    results: Optional[CalculationResults] = None
    workingDirectory: Optional[str] = Field(
        None, description='Path to calculation files'
    )
    errorMessage: Optional[str] = Field(
        None, description='Error details if status is error'
    )


class CalculationSummary(BaseModel):
    id: str = Field(..., description='Unique calculation ID')
    name: str = Field(..., description='Display name')
    path: str = Field(..., description='Directory path')
    date: str = Field(..., description='Date string')
    has_checkpoint: bool = Field(..., description='Whether checkpoint file exists')
    status: CalculationStatus


class Data3(BaseModel):
    calculation: CalculationInstance


class StartCalculationResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data3


class Data4(BaseModel):
    base_directory: str = Field(..., description='Base directory for calculations')
    calculations: List[CalculationSummary]
    count: int = Field(..., description='Number of calculations')


class CalculationListResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data4


class Files(BaseModel):
    checkpoint_exists: bool
    parameters_file_exists: bool
    results_file_exists: bool


class Data5(BaseModel):
    calculation: CalculationInstance
    files: Files


class CalculationDetailsResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data5


class Data6(BaseModel):
    message: str = Field(..., examples=['Calculation renamed successfully.'])
    name: str = Field(..., description='Updated calculation name')


class CalculationUpdateResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data6


class Data7(BaseModel):
    message: str = Field(..., examples=['Calculation deleted successfully'])
    deleted_id: str = Field(..., description='ID of deleted calculation')


class CalculationDeleteResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data7


class OrbitalType(Enum):
    """
    Type of orbital
    """

    core = 'core'
    homo = 'homo'
    lumo = 'lumo'
    virtual = 'virtual'


class OrbitalInfo(BaseModel):
    index: int = Field(..., description='Orbital index (0-based)')
    energy_hartree: float = Field(..., description='Orbital energy in Hartree')
    energy_ev: float = Field(..., description='Orbital energy in eV')
    occupancy: float = Field(
        ..., description='Orbital occupancy (0.0 for virtual, 1.0 or 2.0 for occupied)'
    )
    orbital_type: OrbitalType = Field(..., description='Type of orbital')
    label: Optional[str] = Field(
        None,
        description='Human-readable label (e.g., "HOMO", "LUMO", "HOMO-1", "LUMO+2")',
    )


class Data8(BaseModel):
    orbitals: List[OrbitalInfo] = Field(
        ..., description='List of all molecular orbitals'
    )
    homo_index: int = Field(..., description='Index of HOMO orbital')
    lumo_index: int = Field(..., description='Index of LUMO orbital')
    total_orbitals: int = Field(..., description='Total number of orbitals')
    num_occupied: Optional[int] = Field(None, description='Number of occupied orbitals')
    num_virtual: Optional[int] = Field(None, description='Number of virtual orbitals')


class OrbitalsResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data8


class GenerationParams(BaseModel):
    grid_size: Optional[int] = Field(None, description='Grid size used for generation')
    isovalue_positive: Optional[float] = Field(
        None, description='Positive isovalue used'
    )
    isovalue_negative: Optional[float] = Field(
        None, description='Negative isovalue used'
    )
    file_size_kb: Optional[float] = Field(None, description='Generated file size in KB')


class Data9(BaseModel):
    cube_data: str = Field(..., description='CUBE file content as string')
    orbital_info: OrbitalInfo
    generation_params: GenerationParams


class OrbitalCubeResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: Data9


class ErrorResponse(BaseModel):
    success: bool = Field(..., examples=[False])
    error: str = Field(..., description='Error message')
