[project]
name = "pyscf-pubchem"
version = "0.1.0"
description = "PubChem integration backend for PySCF Native App"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "flask>=3.0.0",
    "pubchempy>=1.0.4",
    "requests>=2.31.0",
    "flask-cors>=4.0.0",
    "certifi>=2025.8.3",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-flask>=1.3.0",
]
