version: '3.8'

services:
  # Development environment extends base compose
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./protos:/protos
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+pymysql://pyscf_user:pyscf_password@mysql:3306/pyscf_dev
      - GRPC_PORT=50051
      - MCP_SERVER_ENABLED=false
      - FLASK_ENV=development
      - DEBUG=true
    command: >
      sh -c "pip install -e . &&
             python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"

  # Flutter Frontend Development
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      - DISPLAY=${DISPLAY:-:0}
    ports:
      - "8080:8080"
      - "9200:9200"  # Flutter DevTools
    depends_on:
      - backend
    
  # MySQL with development-specific settings
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: pyscf_dev
      MYSQL_USER: pyscf_user
      MYSQL_PASSWORD: pyscf_password
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/schema:/docker-entrypoint-initdb.d
      - ./database/test_data:/docker-entrypoint-initdb.d/test_data

volumes:
  mysql_dev_data: