name: CI

on:
  push:
    branches: [ main, develop, "ver.*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache conda environment
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('.github/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: pyscf-env
        environment-file: .github/environment.yml
        python-version: 3.12
        auto-activate-base: false
        use-only-tar-bz2: true
        conda-remove-defaults: true
    
    - name: Install Node.js dependencies
      run: |
        # Configure npm for better network reliability
        npm config set fetch-retries 5
        npm config set fetch-retry-mintimeout 20000
        npm config set fetch-retry-maxtimeout 120000
        npm config set fetch-timeout 300000

        # Retry npm ci up to 3 times on failure
        for i in 1 2 3; do
          npm ci --legacy-peer-deps && break || {
            if [ $i -eq 3 ]; then
              echo "npm ci failed after 3 attempts"
              exit 1
            fi
            echo "npm ci failed, retrying (attempt $i/3)..."
            sleep 10
          }
        done

    - name: Verify conda environment
      shell: bash -l {0}
      run: |
        python scripts/verify-environment.py

    - name: Generate code from OpenAPI spec
      shell: bash -l {0}
      run: |
        npm run codegen:typescript
        cd src/python
        datamodel-codegen --input ../../src/api-spec/openapi.yaml --output generated_models.py --output-model-type pydantic_v2.BaseModel --field-constraints --use-schema-description

    - name: Run Python tests
      shell: bash -l {0}
      run: |
        cd src/python
        python -m pytest tests/ -v

    - name: Build application (production)
      shell: bash -l {0}
      run: |
        # Clean build artifacts
        npm run clean:build-artifacts

        # Build webpack
        npm run build:webpack

        # Build conda-pack (CI version - without conda.sh sourcing)
        rm -rf conda_env
        conda-pack -o conda_env.tar.gz
        mkdir -p conda_env
        tar -xzf conda_env.tar.gz -C conda_env
        rm conda_env.tar.gz
        # Initialize conda environment (fix shebangs)
        ./conda_env/bin/conda-unpack
        echo "Cleaning up development files from conda_env..."
        find conda_env -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
        find conda_env -type f \( -name "*.pyc" -o -name "*.pyo" -o -name "*.pyd" \) -delete
        find conda_env/lib/python*/site-packages -maxdepth 2 -type d \( -name "tests" -o -name "test" \) -exec rm -rf {} + 2>/dev/null || true
        rm -rf conda_env/etc/conda/test-files 2>/dev/null || true
        find conda_env -type f -name ".coverage*" -delete 2>/dev/null || true
        find conda_env -name "*.egg-info" -type d -exec rm -rf {} + 2>/dev/null || true
        echo "✓ Cleanup completed"

        # Validate build
        python scripts/validate-build-completeness.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: |
          dist/
          conda_env/
        retention-days: 7

  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: |
        # Configure npm for better network reliability
        npm config set fetch-retries 5
        npm config set fetch-retry-mintimeout 20000
        npm config set fetch-retry-maxtimeout 120000
        npm config set fetch-timeout 300000

        # Retry npm ci up to 3 times on failure
        for i in 1 2 3; do
          npm ci --legacy-peer-deps && break || {
            if [ $i -eq 3 ]; then
              echo "npm ci failed after 3 attempts"
              exit 1
            fi
            echo "npm ci failed, retrying (attempt $i/3)..."
            sleep 10
          }
        done
    
    - name: Type check TypeScript
      run: npx tsc --noEmit
    
    - name: Check code formatting
      run: npm run format:check